---
title: "Electric Vehicles Analysis"
format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
---

Questions:
Interested to see if cost of fuel correlates to adoption of electric vehciles based on state.

Datasets used:

[Analysis on Electric Car registrations by state as of December 31,2020.](https://afdc.energy.gov/data/10962) Data from U.S. Department of Energy.

EIA U.S. Energy Information Administration for the [Weekly Retail Gasoline and Diesel Prices.](https://www.eia.gov/dnav/pet/PET_PRI_GND_A_EPM0_PTE_DPGAL_A.htm)

According to their definitions the Petroleum Administration for Defense District (PADD) is as follows: PADD 1 (East Coast): PADD 1A (New England): Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont. PADD 1B (Central Atlantic): Delaware, District of Columbia, Maryland, New Jersey, New York, Pennsylvania. PADD 1C (Lower Atlantic): Florida, Georgia, North Carolina, South Carolina, Virginia, West Virginia. PADD 2 (Midwest): Illinois, Indiana, Iowa, Kansas, Kentucky, Michigan, Minnesota, Missouri, Nebraska, North Dakota, Ohio, Oklahoma, South Dakota, Tennessee, Wisconsin. PADD 3 (Gulf Coast): Alabama, Arkansas, Louisiana, Mississippi, New Mexico, Texas. PADD 4 (Rocky Mountain): Colorado, Idaho, Montana, Utah, Wyoming. PADD 5 (West Coast): Alaska (North Slope and Other Mainland), Arizona, California, Hawaii, Nevada, Oregon, Washington.

